version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5000"
    depends_on:
      - db
    environment:
      FLASK_ENV: development
      DATABASE_URL: postgres://krep:199129@db:5432/for_practice
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0 --port=5000

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: for_practice
      POSTGRES_USER: krep
      POSTGRES_PASSWORD: 199129
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  test:
    build: .
    depends_on:
      - db
    environment:
      FLASK_ENV: testing
      DATABASE_URL: postgres://krep:199129@db:5432/for_practice
    volumes:
      - .:/app
    command: ["pytest", "test_app.py", "--maxfail=1", "--disable-warnings", "-q"]

volumes:
  postgres_data: